
export class Persona{

    id_Persona: number; //autogenerated
    
    nombre : String;
    
    apellido: String;
    
    edad: number;
    
    domicilio: String;
    
    nombrePuesto: String;
    
    urlFoto: string ;

    descripcion:String;
    
    constructor(id:number ,nombre:String ,apellido:String ,edad:number ,
        domicilio:String ,nombrePuesto:String,descripcion:String,imagen:string){
            this.id_Persona=id;
            this.nombre=nombre
            this.apellido=apellido;
            this.edad=edad;
            this.domicilio=domicilio;
            this.nombrePuesto=nombrePuesto;
            this.descripcion=descripcion;
            if(imagen.length != 0){
                this.urlFoto=imagen;
            }      
    }

}